definitions:
  config:
    /hst:hst/hst:hosts:
      jcr:primaryType: hst:virtualhosts
      hst:defaultcontextpath: /site
      hst:defaulthostname: localhost
      hst:homepage: root
      hst:locale: en_US
      hst:pagenotfound: error
      hst:scheme: http
      hst:showcontextpath: true
      hst:showport: true
      hst:versioninpreviewheader: true
      /dev-localhost:
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        /localhost:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:channelpath: /hst:hst/hst:channels/myhippoproject
            hst:mountpoint: /hst:hst/hst:sites/myhippoproject
